### PR TITLE
ntcore.value: Use unicode strings in Python 2

### LINKED ISSUE #36: Problem running pynetworktables in python 2.7 with unicode characters
We were using a raspberrypi running network tables for communication with the roborio, but when the roborio creates a table for microsoft camera which has a special character in its description the function NetworkTables.initialize(server=ip) cannot start connection because a UnicodeEncodeError during the handshake.

The debuging return the following errors:

```
DEBUG:nt:client connected
DEBUG:nt:NetworkConnection stopping (<ntcore.network_connection.NetworkConnection object at 0x74469330>)
ERROR:nt:Unhandled exception during handshake
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntcore/network_connection.py", line 240, in _readThreadMain
    handshake_success = self.m_handshake(self, _getMessage, self._sendMessages)
  File "/usr/local/lib/python2.7/dist-packages/ntcore/dispatcher.py", line 488, in _clientHandshake
    msg = get_msg()
  File "/usr/local/lib/python2.7/dist-packages/ntcore/network_connection.py", line 228, in _getMessage
    return Message.read(self.m_stream, decoder, self.m_get_entry_type)
  File "/usr/local/lib/python2.7/dist-packages/ntcore/message.py", line 123, in read
    value = codec.read_value(value_type, rstream)
  File "/usr/local/lib/python2.7/dist-packages/ntcore/wire.py", line 114, in read_value
    return Value.makeString(self.read_string(rstream))
  File "/usr/local/lib/python2.7/dist-packages/ntcore/value.py", line 51, in makeString
    return ValueType(NT_STRING, str(value))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 9: ordinal not in range(128)
INFO:nt:DISCONNECTED roboRIO-3478-FRC.local port 1735 (Robot)
DEBUG:nt:write thread died (<ntcore.network_connection.NetworkConnection object at 0x74ce7230>)
```

tableserror

### PR DESCRIPTION
**Pull request by auscompgeek**
Fixes #36.

### CODE REVIEW

**Comment by virtuald** [comment]
Thanks for doing this, can you add some weird unicode strings (like ©) to the existing unit tests, just so we can verify that it doesn't happen again in the future?

**Comment by auscompgeek** [comment]
Hm. Looks like I misread ntcore.support.compat.

I guess the easy way out would be to consider bytestrings in Python 2 to be raw, but that might be problematic…

`Value.make*` are public APIs, right? Is it documented that `Value.makeString` can take non-strings (converting the value to a string)?

**Comment by virtuald** [comment]
It's only vaguely public... users aren't expected to use ntcore.

**Comment by virtuald** [comment]
Also, keep in mind that Value.makeString is used for incoming values from the network (py2: str, py3: bytes) and from NetworkTable.xxx apis (so.. whatever the user throws at it).

**Comment by auscompgeek** [comment]
From discussion on Gitter:

* Incoming values from the network are actually decoded before being handed to `Value.makeString`.
* We want to let Python 2 users do a plain `table.putString('foo', 'bar')`, instead of having to explicitly pass Unicode strings.

**Comment by virtuald** [comment]
Looks good, can you add a unicode test to the round trips in https://github.com/robotpy/pynetworktables/blob/master/tests/test_api.py?

**Pull request merged**
